_target_: pytorch_forecasting.TimeSeriesDataSet

data_name: stallion
data_dir: ${work_dir}/data/stallion.pkl

batch_size: 128
num_workers: 0

preprocess:
  max_prediction_length: 6

dataset:
  time_idx: 'time_idx'
  target: 'volume'
  weight: null
  group_ids: ['agency', 'sku']
  max_encoder_length: 24
  min_encoder_length: 12
  max_prediction_length: 6
  min_prediction_length: 1
  static_categoricals: ['agency', 'sku']
  static_reals: ['avg_population_2017', "avg_yearly_household_income_2017"]
  time_varying_known_categoricals: ["special_days", "month"]
  time_varying_known_reals: ["time_idx", "price_regular", "discount_in_percent"]
  time_varying_unknown_categoricals: []
  time_varying_unknown_reals: [
      "volume",
      "log_volume",
      "industry_volume",
      "soda_volume",
      "avg_max_temp",
      "avg_volume_by_agency",
      "avg_volume_by_sku"
  ]
  variable_groups:
    special_days: [
        "easter_day",
        "good_friday",
        "new_year",
        "christmas",
        "labor_day",
        "independence_day",
        "revolution_day_memorial",
        "regional_games",
        "fifa_u_17_world_cup",
        "football_gold_cup",
        "beer_capital",
        "music_fest",
    ]
  allow_missing_timesteps: False
  add_relative_time_idx: True
  add_target_scales: True
  add_encoder_length: True
  randomize_length: False
  predict_mode: False

others:
  dataset:
    target_normalizer: GroupNormalizer
    target_normalizer_cfg:
      groups: ["agency", "sku"]
      transformation: softplus